export let mockPosts = [
    {
        id: 1,
        title: 'Getting Started with Spring Boot',
        content: 'Spring Boot makes it easy to create stand-alone, production-grade Spring based Applications that you can "just run".',
        author: 'Blog Author',
        authorId: 1,
        status: 'PUBLISHED',
        createdAt: new Date('2025-08-15T10:30:00Z'),
        updatedAt: new Date('2025-08-15T10:30:00Z'),
    },
    {
        id: 2,
        title: 'Advanced React Hooks',
        content: 'A deep dive into advanced React hooks like useReducer and useContext for complex state management.',
        author: 'Site Admin',
        authorId: 2,
        status: 'PUBLISHED',
        createdAt: new Date('2025-08-14T14:00:00Z'),
        updatedAt: new Date('2025-08-14T14:00:00Z'),
    },
    {
        id: 3,
        title: 'My Next Big Idea (Draft)',
        content: 'This is a secret draft about my next big project. It is not ready for the public yet.',
        author: 'Blog Author',
        authorId: 1,
        status: 'DRAFT',
        createdAt: new Date('2025-08-16T09:00:00Z'),
        updatedAt: new Date('2025-08-16T09:00:00Z'),
    },
    {
        id: 4,
        title: 'A Guide to CSS Grid',
        content: 'Learn the fundamentals of CSS Grid layout with these practical examples and code snippets.',
        author: 'Blog Author',
        authorId: 1,
        status: 'PUBLISHED',
        createdAt: new Date('2025-08-12T11:00:00Z'),
        updatedAt: new Date('2025-08-12T11:00:00Z'),
    },
    {
        id: 5,
        title: 'Understanding Asynchronous JavaScript',
        content: 'Exploring callbacks, promises, and async/await to handle asynchronous operations in JavaScript.',
        author: 'Site Admin',
        authorId: 2,
        status: 'PUBLISHED',
        createdAt: new Date('2025-08-10T18:30:00Z'),
        updatedAt: new Date('2025-08-10T18:30:00Z'),
    },
    {
        id: 6,
        title: 'Introduction to Docker',
        content: 'Containerize your applications with Docker for consistent development and deployment environments.',
        author: 'Blog Author',
        authorId: 1,
        status: 'PUBLISHED',
        createdAt: new Date('2025-08-08T09:20:00Z'),
        updatedAt: new Date('2025-08-08T09:20:00Z'),
    },
    {
        id: 7,
        title: 'The Power of TypeScript',
        content: 'Add static types to your JavaScript projects to catch errors early and improve code quality.',
        author: 'Site Admin',
        authorId: 2,
        status: 'PUBLISHED',
        createdAt: new Date('2025-08-05T15:00:00Z'),
        updatedAt: new Date('2025-08-05T15:00:00Z'),
    },
    {
        id: 8,
        title: 'REST API Design Best Practices',
        content: 'Learn how to design clean, scalable, and easy-to-use RESTful APIs with these industry best practices.',
        author: 'Blog Author',
        authorId: 1,
        status: 'PUBLISHED',
        createdAt: new Date('2025-08-01T12:00:00Z'),
        updatedAt: new Date('2025-08-01T12:00:00Z'),
    },
    {
        id: 9,
        title: 'Future Project Ideas (Draft)',
        content: 'Some private ideas for future blog posts. Not for public view.',
        author: 'Site Admin',
        authorId: 2,
        status: 'DRAFT',
        createdAt: new Date('2025-07-30T10:00:00Z'),
        updatedAt: new Date('2025-07-30T10:00:00Z'),
    },
];

export let mockComments = [
  { id: 101, postId: 1, author: 'Blog Reader', content: 'Great article, thanks for sharing!' },
  { id: 102, postId: 1, author: 'Another User', content: 'I found this very helpful.' },
];

export let mockUsers = [
    { id: 1, name: 'Blog Author', email: 'author@email.com', role: 'AUTHOR' },
    { id: 2, name: 'Site Admin', email: 'admin@email.com', role: 'ADMIN' },
    { id: 3, name: 'Blog Reader', email: 'user@email.com', role: 'READER' },
];